name: Test_workflow

on:
  push:
    branches:
      - 'main'
jobs:
  job:
    name: Testing
    runs-on: self_hosted
    steps:
      - name: My first step
        run: echo Ashwani
      - name: Checkout
        uses: actions/checkout@v5.0.0
